### ISSUE TITLE
Zabbix Sender - does not follow redirects if data is sent to incorrect proxy in Proxy group

### ISSUE THREAD

**Issue by tomijs** [zabbix/python-zabbix-utils#26]
When using sender to send some data to a proxy in a proxy group, sender seemingly is unable to follow redirects, and is not able to successfully send any data. However, if sender checks the proxy, which is monitoring the host in question, first (respectively if the IP of the correct proxy is found first in Agent configuration file "ServerActive" parameter), then it is able to send data. But it cannot send data if a redirect is required. 

#####Sender code:
`sender = Sender(
        use_config=True,
        config_path='/var/lib/snmp_to_json/zabbix_agent2.conf'
)
response = sender.send_value(host[0]["host"],'snmptrap',json.dumps(json_output, indent = 4), int(time.time()))`

#####Configuration file:
`ServerActive=20.20.20.20;10.10.10.10`

#####If correct Proxy IP is found first in Agent configuration file "ServerActive" parameter:
`2024-11-14 11:26:08 Request data: {"request": "sender data", "data": [{"host": "Dummy Switch", "key": "snmptrap", "value": "{\n \"souce\": \"30.30.30.30\",\n \"values\": {\n \"DISMAN-EVENT-MIB::sysUpTimeInstance\":...
2024-11-14 11:26:08 Content of the packet: b'ZBXD\x01m\x01\x00\x00\x00\x00\x00\x00{"request": "sender data", "data": [{"host": "Dummy Switch", "key": "snmptrap", "value": "{\\n \\"souce\\": \\"30.30.30.30\\",\\n \\"values\\": {\\n...
2024-11-14 11:26:08 Trying to send data to 20.20.20.20:10051
2024-11-14 11:26:08 Zabbix response header: b'ZBXD\x01Z\x00\x00\x00\x00\x00\x00\x00'
2024-11-14 11:26:08 Received data: {'response': 'success', 'info': 'processed: 1; failed: 0; total: 1; seconds spent: 0.000253'}
2024-11-14 11:26:08 Response from 20.20.20.20:10051: {'response': 'success', 'info': 'processed: 1; failed: 0; total: 1; seconds spent: 0.000253'}`

#####If secondary proxy IP is found first in Agent configuration file "ServerActive" parameter:
`2024-11-14 11:30:00 Request data: {"request": "sender data", "data": [{"host": "Dummy Switch", "key": "snmptrap", "value": "{\n \"souce\": \"30.30.30.30\",\n \"values\": {\n \"DISMAN-EVENT-MIB::sysUpTimeInstance\":...
2024-11-14 11:30:00 Content of the packet: b'ZBXD\x01m\x01\x00\x00\x00\x00\x00\x00{"request": "sender data", "data": [{"host": "Dummy Switch", "key": "snmptrap", "value": "{\\n \\"souce\\": \\"30.30.30.30\\",\\n \\"values\\": {\\n...
2024-11-14 11:30:00 Trying to send data to 172.22.92.51:10051
2024-11-14 11:30:00 Zabbix response header: b'ZBXD\x01N\x00\x00\x00\x00\x00\x00\x00'
2024-11-14 11:30:00 Received data: {'redirect': {'revision': 7, 'address': '10.10.10.10:10051'}, 'response': 'failed'}
2024-11-14 11:30:00 Response from 172.22.92.51:10051: {'redirect': {'revision': 7, 'address': '10.10.10.10:10051'}, 'response': 'failed'}
2024-11-14 11:30:00 Traceback (most recent call last):
2024-11-14 11:30:00 File "/usr/sbin/snmp_to_json.py", line 115, in <module>
2024-11-14 11:30:00 response = sender.send_value(host[0]["host"],'snmptrap',json.dumps(json_output, indent = 4), int(time.time()))
2024-11-14 11:30:00 File "/var/lib/snmp_to_json/.venv/lib64/python3.12/site-packages/zabbix_utils/sender.py", line 298, in send_value
2024-11-14 11:30:00 return self.send([ItemValue(host, key, value, clock, ns)])
2024-11-14 11:30:00 File "/var/lib/snmp_to_json/.venv/lib64/python3.12/site-packages/zabbix_utils/sender.py", line 265, in send
2024-11-14 11:30:00 resp_by_node = self.__chunk_send(chunk)
2024-11-14 11:30:00 File "/var/lib/snmp_to_json/.venv/lib64/python3.12/site-packages/zabbix_utils/sender.py", line 223, in __chunk_send
2024-11-14 11:30:00 raise socket.error(response)
2024-11-14 11:30:00 OSError
2024-11-14 11:30:00 :
2024-11-14 11:30:00 {'redirect': {'revision': 7, 'address': '10.10.10.10:10051'}, 'response': 'failed'}`

**Comment by hubydu** [comment]
Hi, what is the proposed way to make use of proxy groups? is it only possible to use them with the config file or is there also a parameter i can use?

**Comment by aiantsen** [comment]
Hi @hubydu, thanks for your question.

Proxy groups here are related to the general Zabbix feature, not a particular one in the library or Zabbix API.
Please refer to the [documentation](https://www.zabbix.com/documentation/current/en/manual/web_interface/frontend_sections/administration/proxy_groups) on how to set up and use Proxy groups.
